package fr.wikitahiti.teiki.wikitahiti.dao;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "INTERESTING_POINT".
 */
@Entity
public class InterestingPoint {

    @Id(autoincrement = true)
    private Long id;
    private int interesting_point_id;
    private Integer rate_id;
    private String name;
    private String description;
    private String type;
    private Double latitude;
    private Double longitude;
    private String icon;
    private Integer time_min;
    private Integer time_max;

    // KEEP FIELDS - put your custom fields here
    public static String json_path = "json";

    public static String TAG_NAME = "name";
    public static String TAG_TYPE = "type";
    public static String TAG_DESCRIPTION = "description";
    public static String TAG_TIME_MIN = "time_min";
    public static String TAG_TIME_MAX = "time_max";
    public static String TAG_RATES = "rates";
    public static String TAG_DIFFICULTY = "difficulty";
    public static String TAG_ENDURANCE = "endurance";
    public static String TAG_DANGEROUS = "dangerous";
    public static String TAG_COORDINATE = "coordinate";
    // KEEP FIELDS END

    @Generated(hash = 2109091775)
    public InterestingPoint() {
    }

    public InterestingPoint(Long id) {
        this.id = id;
    }

    @Generated(hash = 469132292)
    public InterestingPoint(Long id, int interesting_point_id, Integer rate_id, String name, String description, String type, Double latitude, Double longitude, String icon, Integer time_min, Integer time_max) {
        this.id = id;
        this.interesting_point_id = interesting_point_id;
        this.rate_id = rate_id;
        this.name = name;
        this.description = description;
        this.type = type;
        this.latitude = latitude;
        this.longitude = longitude;
        this.icon = icon;
        this.time_min = time_min;
        this.time_max = time_max;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getInteresting_point_id() {
        return interesting_point_id;
    }

    public void setInteresting_point_id(int interesting_point_id) {
        this.interesting_point_id = interesting_point_id;
    }

    public Integer getRate_id() {
        return rate_id;
    }

    public void setRate_id(Integer rate_id) {
        this.rate_id = rate_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public Integer getTime_min() {
        return time_min;
    }

    public void setTime_min(Integer time_min) {
        this.time_min = time_min;
    }

    public Integer getTime_max() {
        return time_max;
    }

    public void setTime_max(Integer time_max) {
        this.time_max = time_max;
    }

    // KEEP METHODS - put your custom methods here

	// KEEP METHODS END

}
