package fr.wikitahiti.teiki.wikitahiti.dao;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "TAHITIAN_ACTIVITY".
 */
@Entity
public class TahitianActivity {

    @Id(autoincrement = true)
    private Long id;
    private int TahitianActivity_id;
    private String name;
    private String description;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 295098794)
    public TahitianActivity() {
    }

    public TahitianActivity(Long id) {
        this.id = id;
    }

    @Generated(hash = 1110104458)
    public TahitianActivity(Long id, int TahitianActivity_id, String name, String description) {
        this.id = id;
        this.TahitianActivity_id = TahitianActivity_id;
        this.name = name;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getTahitianActivity_id() {
        return TahitianActivity_id;
    }

    public void setTahitianActivity_id(int TahitianActivity_id) {
        this.TahitianActivity_id = TahitianActivity_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    // KEEP METHODS - put your custom methods here

    // KEEP METHODS END

}
